steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/check-it-a5623/checkit', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/check-it-a5623/checkit']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'checkit', '--image', 'gcr.io/check-it-a5623/checkit', '--region', 'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated', '--max-instances', '3']
images:
- gcr.io/check-it-a5623/checkit